<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>

    <ApplicationIcon>Open_in_Midjourney.ico</ApplicationIcon>

    <AssemblyName>Open in Midjourney</AssemblyName>
    <RootNamespace>OpenInMidjourney</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Open_in_Midjourney.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>